name: Brain games CI

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  tests:
    name: Run project tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install poetry
          make install

      - name: Lint with flake8
        run: make lint
